name: BMW Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Ensure audit directory exists
        run: mkdir -p audit

      - name: Run scraper with audit + verbose
        run: node main_scraper.js --audit --verbose

      - name: Commit updated JSON
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/seen_vehicles.json data/output.json
          git commit -m "Update vehicle data"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CanOfWorms77/BMW_Scraper1.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload audit logs (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: audit-logs
          path: audit/