name: BMW Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BMW_Scraper1  # 👈 this matches the folder GitHub creates

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: BMW_Scraper1  # 👈 this ensures the repo is checked out into BMW_Scraper1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run scraper
        run: node main_scraper.js

      - name: Commit updated JSON
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CanOfWorms77/BMW_Scraper1.git
          git add data/seen_vehicles.json data/output.json
          git commit -m "Update vehicle data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}